flask:
    SECRET_KEY: !ENV ${SECRET_KEY:a25cc816ab5ca48f7634a8b095jf1df51}
    SESSION_COOKIE_HTTPONLY: True
    REMEMBER_COOKIE_HTTPONLY: True
    SESSION_COOKIE_SAMESITE: "Strict"
    BYPASS_LOGIN_REQUIRED: False

server:
    host: !ENV ${SERVER_HOST:127.0.0.1}
    port: !ENV ${SERVER_PORT:5000}

database:
    echo: False
    name: !ENV ${POSTGRES_DB:cleaning_with_heart}
    user: !ENV ${POSTGRES_USER:postgres}
    password: !ENV ${POSTGRES_PASSWORD:postgres}
    host: !ENV ${POSTGRES_HOST:localhost}
    port: !ENV ${POSTGRES_PORT:5432}

twilio:
    sid: !ENV ${TWILIO_SID:_}
    auth_token: !ENV ${TWILIO_AUTH_TOKEN:_}
    sender_phone_number: !ENV ${TWILIO_SENDER_PHONE_NUMBER:_}
    message: !ENV ${TWILIO_MESSAGE:Hello, we remind you that in an hour we will be cleaning your house/apartment. Best regards, Cleaning With Heart!}
